name: slectiv_studio_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  fluentui_system_icons: ^1.0.0
  flutter:
    sdk: flutter
  get: 4.6.6
  get_cli: ^1.8.1
  git: ^2.2.1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/banners/
    - assets/logos/
    - assets/animations/
  uses-material-design: true
