name: slectiv_studio_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

#--------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter


  # Utility Packages

  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  video_player: ^2.8.6
  carousel_slider: ^4.2.1
  git: ^2.2.1

  # Icons
  line_icons: ^2.0.3
  cupertino_icons: ^1.0.6
  fluentui_system_icons: ^1.0.0

  #State Management

  get: ^4.6.6
  get_cli: ^1.8.1
  
  #Firebase
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7

#------------- PACKAGES END -------------#
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# ------------- LOCAL ASSETS -------------#
  assets:
    - assets/lines/
    - assets/banners/
    - assets/logos/
    - assets/videos/
    - assets/images/
    - assets/images/gallery/
    - assets/animations/Onboarding1.json
    - assets/animations/Onboarding2.json
    - assets/animations/Onboarding3.json
    - assets/animations/successBooking.json
    - assets/animations/WaitingToResetPassword.json
  
