name: slectiv_studio_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

#--------------- PACKAGES ---------------#
dependencies:
  better_player: ^0.0.83
  carousel_slider: ^4.2.1
  chewie: ^1.5.0
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  fluentui_system_icons: ^1.0.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_cli: ^1.8.1
  git: ^2.2.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  image_picker: ^1.1.2
  intl: 0.20.2
  line_icons: ^2.0.3
  lottie: ^3.1.2
  rename: ^3.0.2
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.2.0
  url_launcher: ^6.3.0
  video_player: ^2.9.2

#------------- PACKAGES END -------------#
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/slectiv_logo.png"

flutter:
  uses-material-design: true

  # ------------- LOCAL ASSETS -------------#
  assets:
    - assets/lines/
    - assets/banners/
    - assets/logos/
    - assets/videos/
    - assets/images/
    - assets/images/gallery/
    - assets/animations/Onboarding1.json
    - assets/animations/Onboarding2.json
    - assets/animations/Onboarding3.json
    - assets/animations/successBooking.json
    - assets/animations/WaitingToResetPassword.json
